services:
  wh-nginx:
    image: nginx:latest
    volumes:
      - ./app:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    command: /bin/bash -c "exec nginx -g 'daemon off;'"

  wh-php-fpm:
    build:
      context: ./docker
      dockerfile: php-fpm.docker
    volumes:
      - ./app:/app

  wh-php-cli:
    build:
      context: ./docker
      dockerfile: php-cli.docker
    volumes:
      - ./app:/app
      - composer:/root/.composer/cache

  wh-postgres:
    image: postgres:17.2
    volumes:
      - wh-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - "54321:5432"

  wh-node:
    build:
      context: ./
      dockerfile: ./docker/node.docker
    container_name: articles_vue
    volumes:
      - ./vue:/app
    ports:
      - "8888:8080"


volumes:
  wh-postgres:
  composer: