services:
  wh-nginx:
    image: nginx:latest
    volumes:
      - ./app:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    command: /bin/bash -c "exec nginx -g 'daemon off;'"
    depends_on:
      - wh-php-fpm
    networks:
      app_network:
        ipv4_address: 173.20.0.2

  wh-php-fpm:
    build:
      context: ./docker
      dockerfile: php-fpm.docker
    volumes:
      - ./app:/app
    depends_on:
      - wh-redis
      - wh-postgres
    networks:
      app_network:
        ipv4_address: 173.20.0.3

  wh-php-cli:
    build:
      context: ./docker
      dockerfile: php-cli.docker
    volumes:
      - ./app:/app
      - composer:/root/.composer/cache
    depends_on:
      - wh-nginx
      - wh-redis
      - wh-postgres

    networks:
      app_network:
        ipv4_address: 173.20.0.4

  wh-postgres:
    image: postgres:17.2
    volumes:
      - wh-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - "54321:5432"
    networks:
      app_network:
        ipv4_address: 173.20.0.5

  wh-node:
    build:
      context: ./
      dockerfile: ./docker/node.docker
    volumes:
      - ./vue:/app
    ports:
      - "8888:8080"
    networks:
      app_network:
        ipv4_address: 173.20.0.6

  wh-redis:
    image: redis:alpine
    ports:
      - "6381:6379"
    volumes:
      - wh-redis-data:/data
    networks:
      app_network:
        ipv4_address: 173.20.0.7

  wh-worker:
    build:
      context: ./docker
      dockerfile: php-fpm.docker
    volumes:
      - ./app:/app
    command: php artisan queue:work --sleep=3 --tries=3
    depends_on:
      - wh-redis
      - wh-postgres
    networks:
      app_network:
        ipv4_address: 173.20.0.8

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 173.20.0.0/16


volumes:
  wh-postgres:
  wh-redis-data:
  composer: